import React from 'react';
import { 
  Hammer, 
  Home, 
  Zap, 
  Wind, 
  Ruler, 
  Phone, 
  MapPin, 
  Clock, 
  CheckCircle2, 
  ArrowRight,
  Menu,
  X,
  ChevronRight,
  ShieldCheck,
  HardHat,
  Smartphone,
  Mail,
  Sun,
  Moon,
  Thermometer,
  BarChart3,
  Leaf,
  Plus,
  Minus
} from 'lucide-react';

export const Icons = {
  NewBuild: Home,
  Renovation: Hammer,
  Electric: Zap,
  HVAC: Wind,
  Blueprint: Ruler,
  Phone: Phone,
  Location: MapPin,
  Clock: Clock,
  Check: CheckCircle2,
  ArrowRight: ArrowRight,
  Menu: Menu,
  Close: X,
  ChevronRight: ChevronRight,
  Shield: ShieldCheck,
  HardHat: HardHat,
  Mobile: Smartphone,
  Mail: Mail,
  Sun: Sun,
  Moon: Moon,
  Thermometer: Thermometer,
  Chart: BarChart3,
  Eco: Leaf,
  Plus: Plus,
  Minus: Minus
};